### DISCUSSION TITLE
How to classify fault tolerance

### DISCUSSION THREAD

**Discussion by lorenzo-w** [cloudlane-one/k8s-cloud#140] [Announcements]
### Failure domain

With the current cluster setup, three failure domains are possible:

- Pod failure: A single pod goes down due to application error, eviction, etc.
- Node failure: An entire node goes down, meaning all of its pods go down in the long run as well (see #132) due to system or physical error
- Zone failure: All nodes in a zone go down due to network error, power outage etc.

In the long run (minutes or more, again see #132) all these resolve to a specific set of pods failing.

### Auto-recovery

Depending on the failure domain, three auto-recovery types are possible:

- Replication: instant, works if there are other healthy replicas left and the load balancer can just switch to those directly
- Rescheduling: within minutes, works if all replica pods failed, but the app is stateless or stateful with healthy pvc replicas left
- None: if no healthy pvc replicas are left or cluster resources are insufficient for scheduling replacement pods

### Fault tolerance types

You get a fault tolerance type by specifying the auto-recovery mode for each failure domain. Below are definitions for a few sensible types:

- local: for pods that need to run on a specific node
  - single replica + single pv
  - pod: rescheduling
  - node: none
  - zone: none
- zoned: for pods that need to run in a specific zone
  - single replica + zone-replicated pv
  - pod: rescheduling
  - node: rescheduling
  - zone: none
- zoned-ha
  - fully zone-replicated (pods + pvs)
  - pod: replication
  - node: replication
  - zone: none
- backbone
  - single replica + pv replicated across backbone zones
  - pod: rescheduling
  - node: rescheduling
  - zone: rescheduling
- backbone-ha
  - fully replicated across backbone zones (pods + pvs)
  - pod: replication
  - node: replication
  - zone: replication
- backbone-zoned: for pods that can run in any zone, but all in the same one (or which require a specific zone but can temporarily switch to another upon failure)
  - single replica + cross-zone backbone-replicated pv
  - pod: rescheduling
  - node: rescheduling
  - zone: rescheduling
- backbone-zoned-ha
  - zone-replicated pods + cross-zone backbone-replicated pv
  - pod: replication
  - node: replication
  - zone: rescheduling

**Comment by lorenzo-w** [comment]
Following standard config options could cover all these types (except for local):

```yaml
zoning:
  enabled: bool # enabled to enforce scheduling to a specific zone
  name: str # zone name
  soft: bool # set to true to allow pods and pvs to replicate / reschedule to other zones in case of zone failure or low resources
ha:
  enabled: bool
  max_replicas: int
  max_resources: null | object
```
