### ISSUE TITLE
Create redirect ingress for account subdomain

### ISSUE THREAD

**Issue by lorenzo-w** [cloudlane-one/k8s-cloud#116]
Just deploy this ingress together with keycloak:

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: account-console-redir
  namespace: sso-system
  annotations:
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/permanent-redirect: https://id.example.org/realms/master/account
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - account.example.org
      secretName: account.example.org-tls
  rules:
    - host: account.example.org
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: keycloak
                port:
                  name: http
```
