### ISSUE TITLE
Have critical pods auto-recreated when their node goes down

### ISSUE THREAD

**Issue by lorenzo-w** [cloudlane-one/k8s-cloud#132]
As per [this Stackoverflow response](https://stackoverflow.com/a/57805955), one should assign these tolerations to a pod, to have it recreated upon node failure:

```yaml
tolerations:
- key: node.kubernetes.io/not-ready
  effect: NoExecute
  tolerationSeconds: 0
- key: node.kubernetes.io/unreachable
  effect: NoExecute
  tolerationSeconds: 0
```

Possibly use Kyverno to make this the default for all pods in a namespace.
