### ISSUE TITLE
Install operators for common infrastructure components

### ISSUE THREAD

**Issue by lorenzo-w** [cloudlane-one/k8s-cloud#159]
- [ ] [Postgres](https://github.com/zalando/postgres-operator)
- [ ] [MariaDB](https://github.com/mariadb-operator/mariadb-operator)
- [ ] [MongoDB](https://github.com/mongodb/mongodb-kubernetes)
- [ ] [Redis](https://ot-redis-operator.netlify.app/)
- [ ] [RabbitMQ](https://www.rabbitmq.com/kubernetes/operator/operator-overview)
- [ ] [Keycloak Config](https://github.com/epam/edp-keycloak-operator)

**Comment by lorenzo-w** [comment]
Example code for External-secrets Go templating:

```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multiple-passwords
spec:
  refreshInterval: 0s
  target:
    name: my-passwords-secret
    template:
      engineVersion: v2
      data:
        DB_PASSWORD: "{{ randAlphaNum 32 }}"
        API_KEY:    "{{ randAlphaNum 40 }}"
        TOKEN:      "{{ randAlphaNum 64 }}"
```
