### ISSUE TITLE
Standardize and simplify interface of app helm charts

### ISSUE THREAD

**Issue by lorenzo-w** [cloudlane-one/k8s-cloud#161]
- [ ] Keep the main helm values as minimalistic as possible, relying on kustomize for in-depth customization
- [ ] Allow for replacement of infrastructure sub-components with externally supplied ones via kustomize delete patches
  - For server components: delete CR + inject secret with connection details (which would normally be created by CR)
  - For secrets: replace generated [ExternalSecret](https://external-secrets.io/latest/) with one referencing an external store
- [ ] Create a config helm chart(s) for common settings:

```yaml
endpoints:
  - domain: ""
     subdomain: ""
     path: ""
  - ip: ""
     port: ""
     path: ""
service: ""
```

- [ ] Draw common information from centralized cluster secrets in default namespace via [ExternalSecrets](https://external-secrets.io/latest/):

```yaml
org: {}
admin:
  username: ""
  email: ""
smtp: {}
```
